"""Label contract: provenance, schema, and arrival-timing checks.

Labels in production systems are NOT the clean static arrays of offline ML benchmarks.
They arrive late, get corrected, and are generated by policy rules that change over time.

This module formalises:
  - LabelMetadata: who generated the label, what policy, what observation window
  - label_batch_schema: Pandera schema for a batch of ground-truth labels
  - validate_label_batch(): schema enforcement with lazy error collection
  - check_label_arrival(): are enough outcomes confirmed to use this batch?

See: docs/phase3/day20_label_contracts.md for theory.

Usage:
    from data.contracts.label_contract import (
        LabelMetadata,
        DEFAULT_LABEL_METADATA,
        validate_label_batch,
        check_label_arrival,
    )

    meta = DEFAULT_LABEL_METADATA
    validated = validate_label_batch(df)
    arrival = check_label_arrival(df, meta)
    if not arrival["sufficient_for_training"]:
        raise RuntimeError(f"Only {arrival['pct_confirmed']:.0%} labels confirmed")
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any

import pandas as pd
import pandera as pa
from pandera import Check, Column, DataFrameSchema

log = logging.getLogger(__name__)

_VALID_LABEL_SOURCES = ["core_banking", "manual_review", "heuristic", "synthetic"]
_MIN_CONFIRMED_FRACTION = 0.90   # 90% of outcomes must have arrived before training
_DEFAULT_OUTCOME_DELAY_DAYS = 90


@dataclass(frozen=True)
class LabelMetadata:
    """Business context for a label batch.

    Attributes:
        label_source:            Origin system (e.g. "core_banking").
        policy_version:          Labelling rule version (e.g. "v1.2").
                                 A policy change invalidates historical comparisons.
        observation_window_days: How many days of history the features describe.
        outcome_delay_days:      How long after observation_date we wait before
                                 the label is considered final.
        min_confirmed_fraction:  Required fraction of arrived labels before training.
    """

    label_source: str
    policy_version: str
    observation_window_days: int
    outcome_delay_days: int
    min_confirmed_fraction: float = _MIN_CONFIRMED_FRACTION

    def __post_init__(self) -> None:
        if self.label_source not in _VALID_LABEL_SOURCES:
            raise ValueError(
                f"label_source must be one of {_VALID_LABEL_SOURCES}, got {self.label_source!r}"
            )
        if self.outcome_delay_days < 1:
            raise ValueError(f"outcome_delay_days must be >= 1, got {self.outcome_delay_days}")
        if not (0.0 < self.min_confirmed_fraction <= 1.0):
            raise ValueError(f"min_confirmed_fraction must be in (0, 1], got {self.min_confirmed_fraction}")


# ── Pandera schema for label batches ─────────────────────────────────────────

label_batch_schema = DataFrameSchema(
    columns={
        "applicant_id": Column(
            int,
            checks=Check.greater_than(0),
            nullable=False,
            description="Applicant identifier — joins to prediction log and feature dataset",
        ),
        "label": Column(
            int,
            checks=Check.isin([0, 1]),
            nullable=False,
            description="Ground-truth outcome: 1=defaulted, 0=did not default",
        ),
        "label_source": Column(
            str,
            checks=Check.isin(_VALID_LABEL_SOURCES),
            nullable=False,
            description="System that produced this label",
        ),
        "policy_version": Column(
            str,
            nullable=False,
            description="Labelling rule version in effect when this label was generated",
        ),
        "label_timestamp": Column(
            str,
            nullable=False,
            description="ISO-8601 datetime when the label was created",
        ),
        "observation_date": Column(
            str,
            nullable=False,
            description="ISO-8601 date when the features were captured",
        ),
        "outcome_date": Column(
            str,
            nullable=False,
            description="ISO-8601 date when the outcome was confirmed",
        ),
        "is_corrected": Column(
            bool,
            nullable=False,
            description="True if this row replaces a previously issued label",
        ),
    },
    coerce=True,
    strict=False,   # correction_reason and other optional fields are allowed
    name="label_batch_v1",
)


def validate_label_batch(df: pd.DataFrame) -> pd.DataFrame:
    """Validate a label batch DataFrame against label_batch_schema.

    Uses lazy=True to collect ALL violations before raising.

    Raises:
        pa.errors.SchemaErrors: if any validation rule is violated.
    """
    return label_batch_schema.validate(df, lazy=True)


def check_label_arrival(
    df: pd.DataFrame,
    metadata: "LabelMetadata",
) -> dict[str, Any]:
    """Compute what fraction of expected labels have arrived (outcome confirmed).

    A label is considered "arrived" when `outcome_date >= observation_date + outcome_delay_days`.
    We compare this against `min_confirmed_fraction` from the metadata.

    Args:
        df:       Label batch DataFrame (must have outcome_date, observation_date).
        metadata: LabelMetadata specifying the outcome_delay_days and threshold.

    Returns:
        Dict with keys:
            n_total, n_confirmed, pct_confirmed,
            sufficient_for_training, outcome_delay_days, min_required_fraction.
    """
    df = df.copy()
    df["_obs"] = pd.to_datetime(df["observation_date"])
    df["_out"] = pd.to_datetime(df["outcome_date"])
    df["_min_outcome"] = df["_obs"] + pd.Timedelta(days=metadata.outcome_delay_days)
    confirmed = (df["_out"] >= df["_min_outcome"]).sum()

    n_total = len(df)
    pct = float(confirmed / n_total) if n_total > 0 else 0.0
    sufficient = pct >= metadata.min_confirmed_fraction

    if not sufficient:
        log.warning(
            "Label arrival insufficient: %.1f%% confirmed, need %.0f%% (delay=%dd)",
            pct * 100, metadata.min_confirmed_fraction * 100, metadata.outcome_delay_days,
        )
    else:
        log.info(
            "Label arrival OK: %.1f%% of %d labels confirmed (need %.0f%%)",
            pct * 100, n_total, metadata.min_confirmed_fraction * 100,
        )

    return {
        "n_total": n_total,
        "n_confirmed": int(confirmed),
        "pct_confirmed": pct,
        "sufficient_for_training": sufficient,
        "outcome_delay_days": metadata.outcome_delay_days,
        "min_required_fraction": metadata.min_confirmed_fraction,
    }


def check_single_policy_version(df: pd.DataFrame) -> dict[str, Any]:
    """Verify all rows in the batch share the same policy_version.

    Training on mixed policy versions creates an implicit label noise problem:
    the same feature pattern may have different labels under different policies.

    Returns:
        Dict with keys: policy_versions (list), is_consistent (bool).
    """
    if "policy_version" not in df.columns:
        return {"policy_versions": [], "is_consistent": False}

    versions = df["policy_version"].unique().tolist()
    consistent = len(versions) == 1

    if not consistent:
        log.warning("Multiple policy versions in label batch: %s", versions)
    else:
        log.info("Label batch policy version: %s (consistent)", versions[0])

    return {"policy_versions": versions, "is_consistent": consistent}


def check_correction_rate(df: pd.DataFrame, max_rate: float = 0.05) -> dict[str, Any]:
    """Check what fraction of rows are corrections.

    A correction rate > 5% suggests policy instability or upstream data quality issues.

    Args:
        df:       Label batch (must have `is_corrected` column).
        max_rate: Alert threshold (default 5%).

    Returns:
        Dict with keys: n_corrected, n_total, correction_rate, flag.
    """
    if "is_corrected" not in df.columns:
        return {"n_corrected": 0, "n_total": len(df), "correction_rate": 0.0, "flag": False}

    n_corrected = int(df["is_corrected"].sum())
    n_total = len(df)
    rate = float(n_corrected / n_total) if n_total > 0 else 0.0
    flag = rate > max_rate

    if flag:
        log.warning(
            "High label correction rate: %.1f%% (threshold %.0f%%) — possible policy instability",
            rate * 100, max_rate * 100,
        )
    else:
        log.info("Label correction rate: %.1f%% (%d/%d rows)", rate * 100, n_corrected, n_total)

    return {
        "n_corrected": n_corrected,
        "n_total": n_total,
        "correction_rate": rate,
        "flag": flag,
    }


# ── Default metadata for the credit risk project ─────────────────────────────

DEFAULT_LABEL_METADATA = LabelMetadata(
    label_source="core_banking",
    policy_version="v1.0",
    observation_window_days=180,    # 6 months of payment history
    outcome_delay_days=90,          # wait 90 days before label is final
    min_confirmed_fraction=0.90,
)
