apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: credit-risk-serving
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: ml-platform

  source:
    repoURL: https://github.com/arbarikcp/mlops_agentops.git
    targetRevision: main
    path: platform/infra/helm/credit-risk
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: ml-serving

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
